services:
  configurator:
    depends_on:
      redis-cache:
        condition: service_started
      redis-queue:
        condition: service_started
      db:
        condition: service_healthy
    image: "${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-$ERPNEXT_VERSION}"
    pull_policy: "${PULL_POLICY:-always}"
    restart: on-failure
    volumes:
      - "sites:/home/frappe/frappe-bench/sites"
    platform: linux/amd64
    entrypoint:
      - bash
      - "-c"
    command:
      - "ls -1 apps > sites/apps.txt; bench set-config -g db_host $$DB_HOST; bench set-config -gp db_port $$DB_PORT; bench set-config -g redis_cache \"redis://$$REDIS_CACHE\"; bench set-config -g redis_queue \"redis://$$REDIS_QUEUE\"; bench set-config -g redis_socketio \"redis://$$REDIS_QUEUE\"; bench set-config -gp socketio_port $$SOCKETIO_PORT; bench set-config -g chromium_path /usr/bin/chromium-headless-shell;\n"
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: "redis-cache:6379"
      REDIS_QUEUE: "redis-queue:6379"
      SOCKETIO_PORT: 9000
      ERPNEXT_VERSION: "${ERPNEXT_VERSION:-latest}"
      CUSTOM_IMAGE: "${CUSTOM_IMAGE:-frappe/erpnext}"
      CUSTOM_TAG: "${CUSTOM_TAG:-$ERPNEXT_VERSION}"
      PULL_POLICY: "${PULL_POLICY:-always}"
      RESTART_POLICY: "${RESTART_POLICY:-unless-stopped}"
    networks:
      - bench-network
      - mariadb-network
  redis-cache:
    image: "redis:6.2-alpine"
    restart: unless-stopped
  redis-queue:
    image: "redis:6.2-alpine"
    restart: unless-stopped
    volumes:
      - "redis-queue-data:/data"
  backend:
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: "${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-$ERPNEXT_VERSION}"
    pull_policy: "${PULL_POLICY:-always}"
    restart: "${RESTART_POLICY:-unless-stopped}"
    volumes:
      - "sites:/home/frappe/frappe-bench/sites"
    platform: linux/amd64
    networks:
      - mariadb-network
      - bench-network
  db:
    image: "mariadb:11.8"
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - "--connect"
        - "--innodb_initialized"
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--skip-character-set-client-handshake"
      - "--skip-innodb-read-only-compressed"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-123}"
      MARIADB_AUTO_UPGRADE: 1
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      - bench-network
      - mariadb-network
  frontend:
    # image: "${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-$ERPNEXT_VERSION}"
    image: ghcr.io/turingev/erpnext-custom:latest
    pull_policy: "${PULL_POLICY:-always}"
    restart: "${RESTART_POLICY:-unless-stopped}"
    platform: linux/amd64
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: "backend:8000"
      SOCKETIO: "websocket:9000"
      FRAPPE_SITE_NAME_HEADER: "${FRAPPE_SITE_NAME_HEADER:-$$host}"
      UPSTREAM_REAL_IP_ADDRESS: "${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}"
      UPSTREAM_REAL_IP_HEADER: "${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}"
      UPSTREAM_REAL_IP_RECURSIVE: "${UPSTREAM_REAL_IP_RECURSIVE:-off}"
      PROXY_READ_TIMEOUT: "${PROXY_READ_TIMEOUT:-120}"
      CLIENT_MAX_BODY_SIZE: "${CLIENT_MAX_BODY_SIZE:-50m}"
      ROUTER: "${ROUTER:-erpnext-bench_number}"
      SITES_RULE: "${SITES_RULE:-Host(`erpnext.domain.tld`)}"
    volumes:
      - "sites:/home/frappe/frappe-bench/sites"
    depends_on:
      - backend
      - websocket
    networks:
      - coolify
      - bench-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - "traefik.http.services.${ROUTER?ROUTER not set}.loadbalancer.server.port=8080"
      - "traefik.http.routers.${ROUTER}-http.service=${ROUTER}"
      - "traefik.http.routers.${ROUTER}-http.entrypoints=http"
      - "traefik.http.routers.${ROUTER}-http.rule=${SITES_RULE?SITES_RULE not set}"
      - "traefik.http.routers.${ROUTER}-http.middlewares=redirect-to-https"
      - "traefik.http.routers.${ROUTER}-https.rule=${SITES_RULE?SITES_RULE not set}"
      - "traefik.http.routers.${ROUTER}-https.entrypoints=https"
      - "traefik.http.routers.${ROUTER}-https.tls=true"
      - "traefik.http.routers.${ROUTER}-https.service=${ROUTER}"
      - "traefik.http.routers.${ROUTER}-https.tls.certresolver=le"
  websocket:
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: "${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-$ERPNEXT_VERSION}"
    pull_policy: "${PULL_POLICY:-always}"
    restart: "${RESTART_POLICY:-unless-stopped}"
    platform: linux/amd64
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - "sites:/home/frappe/frappe-bench/sites"
    networks:
      - bench-network
      - mariadb-network
  queue-short:
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: "${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-$ERPNEXT_VERSION}"
    pull_policy: "${PULL_POLICY:-always}"
    restart: "${RESTART_POLICY:-unless-stopped}"
    volumes:
      - "sites:/home/frappe/frappe-bench/sites"
    platform: linux/amd64
    command: "bench worker --queue short,default"
    networks:
      - bench-network
      - mariadb-network
  queue-long:
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: "${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-$ERPNEXT_VERSION}"
    pull_policy: "${PULL_POLICY:-always}"
    restart: "${RESTART_POLICY:-unless-stopped}"
    volumes:
      - "sites:/home/frappe/frappe-bench/sites"
    platform: linux/amd64
    command: "bench worker --queue long,default,short"
    networks:
      - bench-network
      - mariadb-network
  scheduler:
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: "${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-$ERPNEXT_VERSION}"
    pull_policy: "${PULL_POLICY:-always}"
    restart: "${RESTART_POLICY:-unless-stopped}"
    volumes:
      - "sites:/home/frappe/frappe-bench/sites"
    platform: linux/amd64
    command: "bench schedule"
    networks:
      - bench-network
      - mariadb-network
volumes:
  sites: null
  redis-queue-data: null
  db-data: null
networks:
  coolify:
    external: true
  mariadb-network:
    external: false
  bench-network:
    name: "${ROUTER}"
    external: false
